USE OHMYDOG
CREATE TABLE EMPRESA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME_EMPRESA CHAR(15) NOT NULL,
    CNPJ CHAR(14) NOT NULL UNIQUE, 
    ENDERECO VARCHAR(100) NOT NULL,
    RAZAO_SOCIAL CHAR(30) NOT NULL,
    CONTATO_ID INT(11) NOT NULL,
    SERVICOS_ID INT(11) NOT NULL, 
    GALERIA_ID INT(11) NOT NULL,
    PRODUTOS_ID INT(11) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CONTATO(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME_COMPLETO VARCHAR(50) NOT NULL,
TELEFONE CHAR(11) NOT NULL, 
EMAIL VARCHAR(50) NOT NULL,
ASSUNTO VARCHAR(50) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
MENSAGEM TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE SERVICOS(
ID INT(11) NOT NULL AUTO_INCREMENT,
PRODUTOS_ID INT(11) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
DESCRICAO TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE GALERIA(
ID INT(11) NOT NULL AUTO_INCREMENT,
FOTOS VARCHAR(100) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
DESCRICAO TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE PRODUTOS(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(50) NOT NULL,
DESCRICAO TEXT,
PRECO DECIMAL(10,2) NOT NULL,
TIPO_PRODUTO VARCHAR(100) NOT NULL,
ANIMAL CHAR(1) NOT NULL DEFAULT "C", /* C = cachorro e G = gato */
EMPRESA_ID INT(11) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);