USE OHMYDOG
CREATE TABLE EMPRESA(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CNPJ CHAR(14) NOT NULL UNIQUE, 
    ENDERECO VARCHAR(100) NOT NULL,
    RAZAO_SOCIAL CHAR(30) NOT NULL,
    CONTATO_ID INT(11) NOT NULL,
    SERVICOS_ID INT(11) NOT NULL, 
    GALERIA_ID INT(11) NOT NULL,
    PRODUTOS_ID INT(11) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CONTATO(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME_COMPLETO VARCHAR(100) NOT NULL,
TELEFONE CHAR(11) NOT NULL, 
EMAIL VARCHAR(100) NOT NULL,
ASSUNTO VARCHAR(100) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
MENSAGEM TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE SERVICO(
ID INT(11) NOT NULL AUTO_INCREMENT,
PRODUTO_ID INT(11) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
DESCRICAO TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);

CREATE TABLE GALERIA(
ID INT(11) NOT NULL AUTO_INCREMENT,
FOTOS VARCHAR(100) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
DESCRICAO TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE PRODUTO(
ID INT(11) NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
DESCRICAO TEXT,
PRECO DECIMAL(10,2) NOT NULL,
TIPO VARCHAR(100) NOT NULL,
EMPRESA_ID INT(11) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);

CREATE TABLE FOTOS(
ID INT(11) NOT NULL AUTO_INCREMENT,
EMPRESA_ID INT(11) NOT NULL,
GALERIA_ID INT(11) NOT NULL,
DESCRICAO TEXT,
PRIMARY KEY(ID),
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
FOREIGN KEY (GALERIA_ID) REFERENCES GALERIA(ID)
);
